# Generated by Django 5.2.1 on 2025-06-08 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0001_initial'),
        ('owasp', '0034_alter_chapter_leaders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('contributor', 'Contributor'), ('mentor', 'Mentor')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_languages', models.JSONField(blank=True, default=list, help_text='Most frequently used programming languages.', null=True, verbose_name='Top Languages')),
                ('preferred_tech_stack', models.JSONField(blank=True, default=list, help_text='Technologies the contributor prefers working with.', null=True, verbose_name='Preferred Tech Stack')),
                ('interested_domains', models.JSONField(blank=True, default=list, help_text='Domains or areas the contributor is interested in.', null=True, verbose_name='Interested Domains')),
                ('issues_worked_on', models.PositiveIntegerField(verbose_name='Issues Worked On')),
                ('prs_open', models.PositiveIntegerField(verbose_name='Open PRs')),
                ('prs_merged', models.PositiveIntegerField(verbose_name='Merged PRs')),
                ('projects', models.ManyToManyField(blank=True, to='owasp.project', verbose_name='Projects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Contributors',
                'db_table': 'nest_contributors',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='List of technologies the mentor is proficient in.', null=True, verbose_name='Tech Stack')),
                ('domains_of_mentorship', models.JSONField(blank=True, default=list, help_text='Areas or domains the mentor provides guidance in.', null=True, verbose_name='Domains of Mentorship')),
                ('years_of_experience', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('mentee_limit', models.PositiveIntegerField(help_text='Maximum number of mentees a mentor can handle at once.', verbose_name='Mentee Limit')),
                ('active_mentees', models.PositiveIntegerField(help_text='Current number of mentees under this mentor.', verbose_name='Active Mentees')),
                ('availability', models.BooleanField(default=True, help_text='Whether the mentor is currently available for mentoring.', verbose_name='Availability')),
                ('mentees', models.ManyToManyField(blank=True, related_name='mentors', to='nest.contributor')),
                ('projects', models.ManyToManyField(blank=True, to='owasp.project', verbose_name='Projects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Mentors',
                'db_table': 'nest_mentors',
                'ordering': ['user__username'],
            },
        ),
    ]
